var data = [{
    fullName: "Ciba Mumu",
    deliveryUnit: "ISD_Iasi",
    dateOfStart: "12 / 03 / 2015",
    lineManager: "Bogdan Volosincu",
    projectManager: "Andrei Ursache",
    jobTitle: "UI Developer",
    grade: "Senior Engineer",
    allocationStatus: "Allocated",
    project: "Trinity Miror",
    date: "10/05/2014"
}, {
    fullName: "Vranceanu Valentin",
    deliveryUnit: "ISD_Iasi",
    dateOfStart: "12 / 03 / 2015",
    lineManager: "Bogdan Volosincu",
    projectManager: "Andrei Ursache",
    jobTitle: "Java Developer",
    grade: "Senior Engineer",
    allocationStatus: "Not Allocated",
    project: "Visa",
    date: "11/06/2015"
}, {
    fullName: "Bogdan Volosincu",
    deliveryUnit: "ISD_Iasi",
    dateOfStart: "12 / 03 / 2015",
    lineManager: "Bogdan Volosincu",
    projectManager: "Andrei Ursache",
    jobTitle: ".Net Developer",
    grade: "Senior Technician",
    allocationStatus: "Allocated",
    project: "Graduate",
    date: "12/07/2016"
}, {
    fullName: "Carmen Budau",
    deliveryUnit: "ISD_Iasi",
    dateOfStart: "12 / 03 / 2015",
    lineManager: "Bogdan Volosincu",
    projectManager: "Andrei Ursache",
    jobTitle: "Bussines Analyst",
    grade: "Engineer",
    allocationStatus: "Not Allocated",
    project: "Denplan",
    date: "13/08/2018"
}, {
    fullName: "Marius Ionescu",
    deliveryUnit: "ISD_Iasi",
    dateOfStart: "12 / 03 / 2015",
    lineManager: "Bogdan Volosincu",
    projectManager: "Andrei Ursache",
    jobTitle: "UI Developer",
    grade: "seniorEngineer",
    allocationStatus: "Allocated",
    project: "Trinity Miror",
    date: "14/09/2019"
}, {
    fullName: "Ionut Popescu",
    deliveryUnit: "ISD_Iasi",
    dateOfStart: "12 / 03 / 2015",
    lineManager: "Bogdan Volosincu",
    projectManager: "Andrei Ursache",
    jobTitle: "Java Developer",
    grade: "Senior Engineer",
    allocationStatus: "Not Allocated",
    project: "Visa",
    date: "05/10/2020"
}, {
    fullName: "Bolboceanu Alexandru",
    deliveryUnit: "ISD_Iasi",
    dateOfStart: "12 / 03 / 2015",
    lineManager: "Bogdan Volosincu",
    projectManager: "Andrei Ursache",
    jobTitle: ".Net Developer",
    grade: "Senior Technician",
    allocationStatus: "Allocated",
    project: "Graduate",
    date: "06/11/2021"
}, {
    fullName: "Cojocaru Iulia",
    deliveryUnit: "ISD_Iasi",
    dateOfStart: "12 / 03 / 2015",
    lineManager: "Bogdan Volosincu",
    projectManager: "Andrei Ursache",
    jobTitle: ".Net Developer",
    grade: "Senior Technician",
    allocationStatus: "Allocated",
    project: "Graduate",
    date: "06/11/2021"
}, {
    fullName: "Tatiana Starciuc",
    deliveryUnit: "ISD_Iasi",
    dateOfStart: "12 / 03 / 2015",
    lineManager: "Bogdan Volosincu",
    projectManager: "Andrei Ursache",
    jobTitle: ".Net Developer",
    grade: "Senior Technician",
    allocationStatus: "Allocated",
    project: "Graduate",
    date: "06/11/2021"
}, {
    fullName: "Ciobanu Iuliana",
    deliveryUnit: "ISD_Iasi",
    dateOfStart: "12 / 03 / 2015",
    lineManager: "Bogdan Volosincu",
    projectManager: "Andrei Ursache",
    jobTitle: "Bussines Analyst",
    grade: "Engineer",
    allocationStatus: "Not Allocated",
    project: "Denplan",
    date: "27/05/2017"
}];